name: nthemis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiodns=3.5.0=py314h06a4308_1
  - aiohappyeyeballs=2.6.1=py314h06a4308_1
  - aiohttp=3.13.2=py314hee96239_0
  - aiosignal=1.4.0=py314h06a4308_0
  - alabaster=1.0.0=py314h06a4308_0
  - alsa-lib=1.2.14=h5eee18b_0
  - annotated-types=0.6.0=py314h06a4308_1
  - aom=3.12.1=h7934f7d_0
  - app-model=0.3.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.4.0=py314h06a4308_0
  - astroid=4.0.2=py314h06a4308_0
  - astropy=7.1.1=py314hc849d88_0
  - astropy-iers-data=0.2025.12.8.0.38.44=py314h06a4308_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - asyncssh=2.21.1=py314h06a4308_0
  - atomicwrites=1.4.0=py_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=py314h06a4308_2
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.17.0=py314h06a4308_0
  - bcrypt=5.0.0=py314h498d7c9_0
  - beautifulsoup4=4.14.2=py314h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=25.11.0=py314h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.6=hf7d4471_0
  - bottleneck=1.4.2=py314h6a40391_1
  - brotlicffi=1.2.0.0=py314h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cachey=0.2.1=pyh9f0ad1d_0
  - cairo=1.18.4=h44eff21_0
  - cattrs=25.3.0=py314hd0c6730_0
  - certifi=2026.01.04=py314h06a4308_0
  - cffi=2.0.0=py314h4eded50_1
  - chardet=5.2.0=py314h06a4308_0
  - charset-normalizer=3.4.4=py314h06a4308_0
  - click=8.2.1=py314h06a4308_1
  - cloudpickle=3.1.2=py314h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=py314h06a4308_0
  - contourpy=1.3.3=py314hdb19cb5_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=46.0.3=py314h0a354b3_0
  - cycler=0.12.1=py314h06a4308_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - cytoolz=1.1.0=py314h47b2149_1
  - dask-core=2025.11.0=py314h06a4308_1
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.16=py314hbdd6827_1
  - decorator=5.2.1=py314h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.18=py314h06a4308_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.4.0=py314h06a4308_0
  - docstring-to-markdown=0.17=py314h06a4308_0
  - docstring_parser=0.17.0=py314h06a4308_0
  - docutils=0.21.2=py314h06a4308_1
  - donfig=0.8.1.post1=py314h06a4308_0
  - eigen=5.0.1=hf04f85b_0
  - executing=2.2.1=py314h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - fftw=3.3.10=hbd630f4_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.60.1=py314hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - freetype-py=2.5.1=py314hd859747_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.8.0=py314hbdd6827_0
  - fsspec=2025.10.0=py314h6fa48dc_0
  - fzf=0.67.0=he404d97_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - google-crc32c=1.6.0=py314h3eab9ac_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - gstreamer-orc=0.4.41=h5eee18b_0
  - harfbuzz=11.4.5=h15599e2_0
  - hdf5=1.14.6=nompi_h1b119a7_104
  - heapdict=1.0.1=pyhd3eb1b0_0
  - hsluv=5.0.4=py314h06a4308_0
  - icu=75.1=he02047a_0
  - idna=3.11=py314h06a4308_0
  - imageio=2.37.2=py314h6fa48dc_0
  - imagesize=1.4.1=py314h06a4308_0
  - importlib-metadata=8.7.0=py314h06a4308_0
  - in-n-out=0.2.1=pyhd8ed1ab_1
  - inflection=0.5.1=py314h06a4308_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipycanvas=0.14.3=pyhcf101f3_0
  - ipyevents=2.0.4=pyhbbac1ac_0
  - ipykernel=6.31.0=py314h6fa48dc_0
  - ipympl=0.9.7=py314h06a4308_0
  - ipython=9.7.0=py314h06a4308_0
  - ipython_pygments_lexers=1.1.1=py314h06a4308_0
  - ipywidgets=8.1.7=py314h06a4308_0
  - isort=5.9.3=pyhd3eb1b0_0
  - jansson=2.14=h5eee18b_1
  - jaraco.classes=3.4.0=py314h06a4308_0
  - jaraco.context=6.0.0=py314h06a4308_0
  - jaraco.functools=4.1.0=py314h06a4308_0
  - jedi=0.19.2=py314h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=1.2.1=py314h498d7c9_0
  - jinja2=3.1.6=py314h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - joblib=1.5.2=py314h06a4308_0
  - jsonschema=4.25.0=py314h06a4308_1
  - jsonschema-specifications=2025.9.1=py314h06a4308_0
  - jupyter_client=8.6.3=py314h06a4308_1
  - jupyter_core=5.9.1=py314h06a4308_0
  - jupyterlab_pygments=0.3.0=py314h06a4308_0
  - jupyterlab_widgets=3.0.15=py314h06a4308_0
  - keyring=25.7.0=py314h06a4308_0
  - kiwisolver=1.4.9=py314h24d9097_0
  - krb5=1.21.3=h723845a_4
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py314h06a4308_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif=1.3.0=h3539ee5_0
  - libcap=2.77=h3ff7636_0
  - libclang-cpp20.1=20.1.8=default_h4fcecc7_0
  - libclang13=20.1.8=default_hee3e7a4_0
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=hc93bc37_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hf80d704_0
  - libitk=5.4.4=h8db0697_0
  - libjpeg-turbo=3.1.2=hfdadbec_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm20=20.1.8=h465586c_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libogg=1.3.5=h27cfd23_1
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=heac8642_0
  - libspatialindex=2.1.0=hf7d4471_0
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.0=hc4654cb_2
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvmlite=0.46.0=py314ha853ca8_0
  - lmdb=0.9.31=hb25bd0a_0
  - locket=1.0.0=py314h06a4308_0
  - loguru=0.7.3=py314h06a4308_0
  - lsprotocol=2025.0.0=pyhe01879c_0
  - lz4-c=1.9.4=h6a678d5_1
  - magicgui=0.10.1=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=py314h06a4308_0
  - markupsafe=3.0.2=py314h5eee18b_0
  - matplotlib=3.10.7=py314h06a4308_0
  - matplotlib-base=3.10.7=py314h54cb298_0
  - matplotlib-inline=0.2.1=py314h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.2=py314h06a4308_0
  - mistune=3.1.2=py314h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py314hacdc0fc_0
  - mkl_fft=2.1.1=py314h2be417e_0
  - mkl_random=1.3.0=py314hda4e5d8_0
  - more-itertools=10.8.0=py314h06a4308_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.1=py314h6a678d5_0
  - multidict=6.7.0=py314hee96239_0
  - mypy_extensions=1.0.0=py314h06a4308_0
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - napari=0.6.0=pyhd8ed1ab_0
  - napari-assistant=0.4.4=pyhd8ed1ab_0
  - napari-base=0.6.0=pyh9208f05_0
  - napari-console=0.1.4=pyhc04f84c_0
  - napari-plugin-engine=0.2.0=pyha07c04f_3
  - napari-plugin-manager=0.1.9=pyhd8ed1ab_0
  - napari-simpleitk-image-processing=0.4.9=pyhd0adb26_1
  - napari-skimage-regionprops=0.10.1=pyhd8ed1ab_0
  - napari-svg=0.2.1=pyha07c04f_0
  - napari-time-slicer=0.5.0=pyha07c04f_1
  - napari-tools-menu=0.1.20=pyha07c04f_0
  - napari-workflows=0.2.10=pyhd8ed1ab_0
  - nbclient=0.10.2=py314h06a4308_0
  - nbconvert=7.16.6=py314h06a4308_0
  - nbconvert-core=7.16.6=py314h06a4308_0
  - nbconvert-pandoc=7.16.6=py314h06a4308_0
  - nbformat=5.10.4=py314h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - npe2=0.7.9=pyhd8ed1ab_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numba=0.63.1=py314h45d1962_0
  - numcodecs=0.16.3=py314h9e34fa4_0
  - numexpr=2.14.1=py314hc3af6af_0
  - numpy=2.3.5=py314hc4ca38b_0
  - numpy-base=2.3.5=py314h7c74580_0
  - numpydoc=1.9.0=py314h06a4308_0
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=py314h06a4308_1
  - pandas=2.3.3=py314hda4e5d8_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py314h06a4308_0
  - parso=0.8.5=py314h06a4308_0
  - partd=1.4.2=py314h06a4308_0
  - pathspec=0.12.1=py314h06a4308_1
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py314h06a4308_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.3.0=py314hcbdf0ca_1
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py314h06a4308_0
  - pluggy=1.5.0=py314h06a4308_0
  - ply=3.11=py314h06a4308_1
  - pooch=1.8.2=py314h06a4308_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.52=py314h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.4.1=py314h47b2149_0
  - psutil=7.0.0=py314hee96239_1
  - psygnal=0.12.0=py314h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pulseaudio-client=17.0=hac146a9_1
  - pure_eval=0.2.3=py314h06a4308_0
  - pycares=4.10.0=py314h4866c75_0
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.12.4=py314h06a4308_0
  - pydantic-compat=0.1.2=pyhd8ed1ab_0
  - pydantic-core=2.41.5=py314h498d7c9_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyerfa=2.0.1.5=py314hfdf79b4_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=py314h06a4308_0
  - pygments=2.19.2=py314h06a4308_0
  - pyjwt=2.10.1=py314h06a4308_1
  - pylint=4.0.3=py314h06a4308_0
  - pylint-venv=3.0.3=py314h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.6.0=py314h2630517_0
  - pyopengl=3.1.10=py314h06a4308_0
  - pyparsing=3.2.5=py314h06a4308_0
  - pyperclip=1.11.0=pyha804496_0
  - pyproject_hooks=1.2.0=py314h06a4308_1
  - pyqt=5.15.11=py314h92491ac_2
  - pyqt5-sip=12.17.0=py314ha160325_2
  - pyqtgraph=0.14.0=pyhd8ed1ab_0
  - pyqtwebengine=5.15.11=py314hb4c45cb_2
  - pysocks=1.7.1=py314h06a4308_1
  - python=3.14.2=h90eec9f_101_cp314
  - python-build=1.3.0=py314h06a4308_1
  - python-dateutil=2.9.0post0=py314h06a4308_2
  - python-dotenv=1.1.0=py314h06a4308_0
  - python-fastjsonschema=2.21.2=py314h06a4308_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-ruff=2.3.0=pyhcf101f3_0
  - python-lsp-server=1.14.0=pyh332efcf_0
  - python-lsp-server-base=1.14.0=pyhd8ed1ab_0
  - python-slugify=8.0.4=py314h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytokens=0.3.0=py314h06a4308_0
  - pytoolconfig=1.2.6=py314h06a4308_0
  - pytz=2025.2=py314h06a4308_0
  - pyuca=1.2=py314h06a4308_1
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0.3=py314h591646f_0
  - pyzmq=27.1.0=py314hcf8288c_1
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py314h06a4308_0
  - qt-main=5.15.15=h993ce98_3
  - qt-webengine=5.15.15=h2da670d_3
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.7.0=py314h06a4308_0
  - qtconsole-base=5.7.0=pyha770c72_0
  - qtpy=2.4.3=py314h06a4308_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py314h06a4308_0
  - requests=2.32.5=py314h06a4308_1
  - rich=14.2.0=py314h06a4308_0
  - roman-numerals-py=3.1.0=py314h06a4308_0
  - rope=1.14.0=py314h06a4308_0
  - rpds-py=0.28.0=py314h498d7c9_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.12.0=py314hc6f7160_0
  - scikit-learn=1.8.0=py314h973aee8_0
  - scipy=1.16.3=py314h3d0cd3c_0
  - secretstorage=3.4.0=py314h3e8c6aa_0
  - setuptools=80.9.0=py314h06a4308_0
  - shellingham=1.5.4=py314h06a4308_0
  - simpleitk=2.5.2=py314h0bdf2a0_1
  - sip=6.10.0=py314ha160325_1
  - six=1.17.0=py314h06a4308_0
  - snowballstemmer=3.0.1=py314h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py314h06a4308_0
  - sphinx=8.2.3=py314h893fd2c_1
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - spyder=6.1.2=hd8ed1ab_0
  - spyder-base=6.1.2=linux_pyh62a8a7d_0
  - spyder-kernels=3.1.2=py314h6fa48dc_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py314h06a4308_0
  - stackview=0.18.0=pyhd8ed1ab_0
  - superqt=0.7.6=py314hd77be10_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py314h6fa48dc_1
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.5.1=py314h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.2.1=py314h06a4308_0
  - tomli-w=1.2.0=pyhd3eb1b0_0
  - tomlkit=0.13.3=py314h06a4308_0
  - toolz=1.1.0=py314h06a4308_0
  - tornado=6.5.1=py314h5eee18b_0
  - tqdm=4.67.1=py314h6fa48dc_1
  - traitlets=5.14.3=py314h06a4308_0
  - typer=0.20.0=py314h06a4308_0
  - typer-slim=0.20.0=py314h06a4308_0
  - typer-slim-standard=0.20.0=py314h06a4308_0
  - typing-extensions=4.15.0=py314h06a4308_0
  - typing-inspection=0.4.2=py314h06a4308_0
  - typing_extensions=4.15.0=py314h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ujson=5.11.0=py314h7354ed3_0
  - urllib3=2.6.1=py314h06a4308_0
  - uvloop=0.22.1=py314h939ff40_1
  - vispy=0.14.3=py314h03dd93b_0
  - watchdog=6.0.0=py314h06a4308_0
  - wcwidth=0.2.13=py314h06a4308_0
  - webencodings=0.5.1=py314h06a4308_2
  - whatthepatch=1.0.7=py314h06a4308_0
  - widgetsnbextension=4.0.14=py314h06a4308_0
  - wordcloud=1.9.4=py314h5eee18b_0
  - wrapt=1.17.0=py314h5eee18b_0
  - wurlitzer=3.1.1=py314h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xclip=0.13=hb9d3cd8_4
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxcursor=1.2.3=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxmu=1.2.1=h9b100fa_1
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxt=1.3.1=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xsel=1.2.1=hb9d3cd8_6
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.43.0=py314h06a4308_0
  - yarl=1.22.0=py314hee96239_0
  - zarr=3.1.5=pyhcf101f3_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=py314h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - atlas-fit==1.0.3
      - mpl-point-clicker==0.4.1
      - networkx==3.6.1
      - pyqt6==6.10.2
      - pyqt6-qt6==6.10.1
      - pyqt6-sip==13.10.3
      - qollib==0.1.3
      - scikit-image==0.26.0
      - spectator==0.1.0
      - spectroflat==2.1.0
      - themis==0.1.0
      - tifffile==2025.12.20
prefix: /home/franziskaz/miniconda3/envs/nthemis
