name: themis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=pyhf64b827_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alsa-lib=1.2.15.3=hb03c661_0
  - aom=3.12.1=h7934f7d_0
  - arrow=1.4.0=pyhcf101f3_0
  - astroid=4.0.3=py314hdafbbf9_0
  - astropy=7.1.1=py314hc849d88_0
  - astropy-iers-data=0.2026.1.19.0.42.31=py314h06a4308_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - asyncssh=2.21.1=py314h06a4308_0
  - atk-1.0=2.38.0=h04ea711_2
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhcf101f3_2
  - backports.zstd=1.3.0=py314h680f03e_0
  - bcrypt=5.0.0=py314h2e6c369_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=26.1.0=pyh866005b_0
  - blas=1.0=mkl
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli-python=1.2.0=py314h3de4e8d_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - cattrs=25.3.0=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py314h4eded50_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314hdb19cb5_0
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.14.2=py314hd8ed1ab_101
  - cryptography=46.0.4=py314h7fe84b3_0
  - cycler=0.12.1=py314h06a4308_0
  - cyrus-sasl=2.1.28=h83b0a09_4
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.20=py314h42812f9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_1
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.1=pyhcf101f3_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h7354ed3_4
  - flake8=7.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py314h47b2149_0
  - freetype=2.14.1=hf5b9546_0
  - fribidi=1.0.16=h9fb5f84_0
  - frozenlist=1.7.0=pyhf298e5d_0
  - fzf=0.67.0=h6138981_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - giflib=5.2.2=hd590300_0
  - glib=2.86.3=h617169b_0
  - glib-tools=2.86.3=h9fad118_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=9.0.0=h78e8752_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtk2=2.24.33=h280cfa0_4
  - gts=0.7.6=h977cf35_4
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h79d275a_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.31.0=pyha191276_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isort=7.0.0=pyhd8ed1ab_0
  - jansson=2.15.0=h280c20c_0
  - jaraco.classes=3.4.0=pyhcf101f3_3
  - jaraco.context=6.1.0=pyhcf101f3_0
  - jaraco.functools=4.4.0=pyhcf101f3_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jeepney=0.9.0=pyhd8ed1ab_0
  - jellyfish=1.2.1=py314ha5689aa_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9f=h5ce9db8_0
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - keyring=25.7.0=pyha804496_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py314h24d9097_0
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_hbbce691_0
  - libavif=1.3.0=h3539ee5_0
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libclang=14.0.6=default_h7634d5b_1
  - libclang13=14.0.6=default_h9986a30_1
  - libcups=2.4.15=hbe4054b_0
  - libcurl=8.18.0=h3506a8c_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgd=2.3.3=h536bbd8_4
  - libgfortran=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hfac485b_1
  - libkrb5=1.22.1=h6d2bf13_0
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.54=hee55ce4_0
  - libpq=17.6=h5ca1609_1
  - libprotobuf=5.29.3=h501fc15_0
  - librsvg=2.58.0=hadf69e7_1
  - libsodium=1.0.20=heac8642_0
  - libspatialindex=2.1.0=he57a185_0
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lsprotocol=2025.0.0=pyhe01879c_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib=3.10.8=py314h06a4308_0
  - matplotlib-base=3.10.8=py314h54cb298_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mesalib=25.1.5=h31e3550_0
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py314hacdc0fc_0
  - mkl_fft=2.1.1=py314h2be417e_0
  - mkl_random=1.3.0=py314hda4e5d8_0
  - more-itertools=10.8.0=pyhcf101f3_1
  - multidict=6.7.0=pyh62beb40_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - mysql=8.4.0=h721767e_2
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert=7.17.0=h14065e2_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbconvert-pandoc=7.17.0=hc3985f0_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numpy=2.4.1=py314hc4ca38b_0
  - numpy-base=2.4.1=py314h7c74580_0
  - numpydoc=1.10.0=pyhcf101f3_0
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py314h06a4308_1
  - pandoc=3.8.3=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=hadf4263_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=1.0.4=pyhd8ed1ab_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py314hd9fd23a_0
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=pyhe1237c8_0
  - psutil=7.2.2=py314h0f05182_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyerfa=2.0.1.5=py314hfdf79b4_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=4.0.4=pyhcf101f3_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.6.2=py314h5bd0f2a_0
  - pyparsing=3.2.5=py314h06a4308_0
  - pyqt=5.15.11=py314h144e999_0
  - pyqt5-sip=12.17.0=py314hee96239_0
  - pyqt6-sip=13.10.2=py314hee96239_0
  - pyqtgraph=0.14.0=pyhd8ed1ab_0
  - pyqtwebengine=5.15.11=py314hf9d9379_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.2=h90eec9f_101_cp314
  - python-dateutil=2.9.0post0=py314h06a4308_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.14.2=h4df99d1_101
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-ruff=2.3.0=pyhcf101f3_0
  - python-lsp-server=1.14.0=pyh332efcf_0
  - python-lsp-server-base=1.14.0=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.14=2_cp314
  - pytokens=0.3.0=pyhcf101f3_0
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.3=py314h591646f_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.2=hb6262e9_12
  - qt-webengine=5.15.9=he2071f7_8
  - qtawesome=1.4.1=pyh9208f05_0
  - qtbase=6.9.2=h1fa0d2d_6
  - qtconsole=5.7.0=pyhd8ed1ab_0
  - qtconsole-base=5.7.0=pyha770c72_0
  - qtdeclarative=6.9.2=h55666de_1
  - qtpy=2.4.3=pyhd8ed1ab_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.1=pyhcf101f3_0
  - roman-numerals=4.1.0=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.30.0=py314h2e6c369_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.14.14=h40fa522_1
  - scikit-learn=1.8.0=np2py314hf09ca88_1
  - scipy=1.16.3=py314h3d0cd3c_0
  - secretstorage=3.4.1=py314hdafbbf9_0
  - setuptools=80.10.1=py314h06a4308_0
  - sip=6.12.0=py314h695c4d2_0
  - six=1.17.0=py314h06a4308_0
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sphinx=9.1.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spirv-tools=2025.1=hdb19cb5_0
  - spyder=6.1.2=hd8ed1ab_0
  - spyder-base=6.1.2=linux_pyh62a8a7d_0
  - spyder-kernels=3.1.2=unix_pyh707e725_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.7=pyh9208f05_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.4.0=pyhcf101f3_0
  - tomlkit=0.14.0=pyha770c72_0
  - tornado=6.5.4=py314h47b2149_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - ujson=5.11.0=py314h8c728da_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - watchdog=6.0.0=py314hdafbbf9_2
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.5.2=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wrapt=2.0.1=py314h5bd0f2a_1
  - wurlitzer=3.1.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.22.0=pyh7db6752_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - atlas-fit==1.0.3
      - imageio==2.37.2
      - lazy-loader==0.4
      - mpl-point-clicker==0.4.1
      - networkx==3.6.1
      - pandas==3.0.0
      - pyqt6==6.10.2
      - pyqt6-qt6==6.10.2
      - qollib==0.1.3
      - scikit-image==0.26.0
      - spectator==0.2.0
      - spectroflat==2.1.0
      - themis==0.2.0
      - tifffile==2026.1.28
prefix: /home/franziskaz/miniconda3/envs/themis
